root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/vjvector"
  cmd = "go build -o ./tmp/vjvector ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "deploy", "deployments", "docs", "examples", "scripts", "tools"]
  exclude_file = []
  exclude_regex = ["_test.go", "_test.go$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/vjvector serve --config ./config.cluster.yaml"
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "yaml", "yml"]
  include_file = []
  kill_delay = "0.5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true
