# golangci-lint v2 configuration
version: 2

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - gocritic
    - revive

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
